algorithm_lab: quicksort2.c interchange.c partition.c test_quicksort2.c test_select2 insertionsort.c
	gcc -o quicksort2 -g test_quicksort2.c -g quicksort2.c -g partition.c -g interchange.c -lm
	gcc -o select2 -g test_select2.c -g select2.c -g partition.c -g interchange.c -g insertionsort.c -lm

